# Python Tutorial II - Numpy

* Why use Numpy
* N-dimensional arrays (`ndarray`)
  * Broadcasting
* Save and load

## Why numpy

In one sentence - Python lists are slow.

This is because it trades efficiency for usability (easy to use, but with many levels of actions).

Numpy uses C/C++ which are far more efficient than Python.

## Arrays

Arrays or N-dimensional arrays are the main data type in Numpy.

In [1]:
import numpy as np

In [52]:
np.ndarray?

### Creating an array

In [5]:
# Create a list
my_list = list(range(1, 25))

In [7]:
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [8]:
# Make a np array from the list
arr = np.array(my_list)

In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [10]:
arr.dtype

dtype('int64')

Numpy has 18 data types:

https://numpy.org/doc/stable/user/basics.types.html

Common ones are:
* `uint8`, `int8`
* `float16`, `float32`, `float64`


In [14]:
arr.astype(np.float16)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float16)

In [15]:
arr.astype(np.uint8)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=uint8)

In [17]:
# Get the shape
arr.shape

(24,)

In [19]:
arr.reshape((6,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [20]:
arr.reshape((2, 3, 4))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [29]:
# astype or reshape will create a new array object
# Hence the original object won't be change
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
arr2 = arr.reshape((2,3,4))

In [22]:
arr2.shape

(2, 3, 4)

In [38]:
# Flatten an array
arr2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

Another way to create an array is to call the numpy functions.

In [54]:
np.zeros((3,4), dtype=np.float16)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [56]:
np.arange(1, 25).reshape((3,8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [57]:
# Others
# np.zeros_like, np.ones, np.ones_like, np.eye

## Operations

### Uni-operand

Numpy provides lots of math functions. It will calculate the element-wise result, returning an array with the same size.

You can think of this is applying a function in a for loop on each element.

In [58]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10])

In [59]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [60]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [61]:
np.tan(arr)

array([ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,  1.15782128e+00,
       -3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
        4.63021133e-01,  7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
        3.49391565e+00, -1.13731371e+00,  1.51589471e-01,  2.23716094e+00,
       -1.52749853e+00,  8.85165604e-03,  1.58815308e+00, -2.13489670e+00])

### To do

Define a function that takes an angle ($Θ$) and returns the matrix as an array.

  $R = \begin{pmatrix}
  \sin(Θ) & -\cos(Θ) \\
  -\tan(Θ) & \cot(Θ) \\
  \end{pmatrix}$

In [ ]:
# Answer
def rotation_matrix(theta):
    # Answer
    pass




### Bi-operand

When two operands are involved, it will first check the shape:
* If the shape matches, it will do an element-wise operation
* If it doesn't match,
  * If one shape is a perfect subsect of the other, it will do what's called a **broadcasting**.
    * Hence for a scalar, it can always do broadcasting, e.g. `array([10, 11, 23]) + 1`
  * Else it will trigger an error

In [39]:
# Same shape
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [40]:
# Broadcasting
np.array([1,2,3]) + 4

array([5, 6, 7])

In [41]:
# Broadcasting
np.array([[1,2,3], [4,5,6]]) + np.array([1,1,1])

array([[2, 3, 4],
       [5, 6, 7]])

In [42]:
# Error
np.array([[1,2,3], [4,5,6]]) + np.array([1,1])

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

## Save and load

In [48]:
np.save('arr2.npy', arr2)

In [49]:
arr2_loaded = np.load('arr2.npy')

In [50]:
arr2_loaded

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### To do
* Cast `arr` to `float64` as variable `arr3`.
* Save it as file `arr3.npy`.
* Load it as `arr3_loaded` and make sure it's the same as `arr3`

In [ ]:
# Answer





## Walk through of a sample MRI assignment

https://github.com/sunyu0410/5020-python-tutorial/blob/main/PHYS5011_MRI_Assignment_Python_Tutorial_Demo.ipynb

This week, work out
* What do each of the functions do?
* Which steps may involve broadcasting?