# Reading Materials and Exercise II - Numpy

Read the following topics if not the entire document: [*NumPy: the absolute basics for beginners*](https://numpy.org/doc/stable/user/absolute_beginners.html)

* [Indexing and slicing](https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing)
* [Broadcasting](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting)


In [ ]:
import numpy as np

## Roatation

You'll generate a 2D rotation metrix, apply some noise and use it to transform existing points.

In [7]:
# Setup (Do not change.)
np.random.seed(1234)
points = np.random.random((30, 2)) * 10 - 5

1. Define a function `get_rot_mat()` that takes an angle ($Θ$) and returns the rotation matrix R as an array.

  $R = \begin{pmatrix}
  \cos(Θ) & -\sin(Θ) \\
  \sin(Θ) & \cos(Θ) \\
  \end{pmatrix}$

2. Get the rotation matrix of pi/4, assigned as `r45`

3. Generate some Gausian noise for `r45`, assigned in `noise`, with a mean of 0.1 and standard deviation of 0.1. Use `np.random.normal()`. This should element-wise.

4. Use matrix multiplication `np.matmul()` to get the transformed coordinate of each each point.

## Element operations

If you are cook, this is your cutting skills. Take a paper, figure out the pattern and strategy, then start coding.

In [77]:
# Setup (Do not change)
arr = np.arange(1, 25).reshape(2,3,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### To do
Modify from `arr` to the following data. All examples can be done using no more than 3 lines.

In [73]:
# Hint: notice how many brackets

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  0],
         [ 9,  0, 11,  0]],

        [[13,  0, 15,  0],
         [17,  0, 19, 20],
         [21, 22, 23, 24]]]])

array([[[-3, -2, -1,  0],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]])

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

In [32]:
# Hint: guess what function is applied

array([[[0.        , 1.        , 1.5849625 , 2.        ],
        [2.32192809, 2.5849625 , 2.80735492, 3.        ],
        [3.169925  , 3.32192809, 3.45943162, 3.5849625 ]],

       [[3.70043972, 3.80735492, 3.9068906 , 4.        ],
        [4.08746284, 4.169925  , 4.24792751, 4.32192809],
        [4.39231742, 4.45943162, 4.52356196, 4.5849625 ]]])

array([[[ 0,  0,  0,  0],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

array([[[ 0,  2,  3,  4],
        [ 0,  6,  7,  8],
        [ 0, 10, 11, 12]],

       [[ 0, 14, 15, 16],
        [ 0, 18, 19, 20],
        [ 0, 22, 23, 24]]])

array([[[ 0,  2,  0,  4],
        [ 0,  6,  0,  8],
        [ 0, 10,  0, 12]],

       [[ 0, 14,  0, 16],
        [ 0, 18,  0, 20],
        [ 0, 22,  0, 24]]])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  0,  0,  0,  0, 12],
       [13,  0,  0,  0,  0, 18],
       [19, 20, 21, 22, 23, 24]])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  0,  9,  0, 11,  0],
       [13,  0, 15,  0, 17,  0],
       [19, 20, 21, 22, 23, 24]])

array([ 0,  2,  3,  0,  5,  6,  0,  8,  9,  0, 11, 12,  0, 14, 15,  0, 17,
       18,  0, 20, 21,  0, 23, 24])

array([[[ 0. +0.j,  2. +4.j,  3. +6.j,  0. +0.j],
        [ 5.+10.j,  6.+12.j,  0. +0.j,  8.+16.j],
        [ 9.+18.j,  0. +0.j, 11.+22.j, 12.+24.j]],

       [[ 0. +0.j, 14.+28.j, 15.+30.j,  0. +0.j],
        [17.+34.j, 18.+36.j,  0. +0.j, 20.+40.j],
        [21.+42.j,  0. +0.j, 23.+46.j, 24.+48.j]]])